### ISSUE TITLE
Merge python-tools branch

### ISSUE THREAD

**Issue by patcon** [patcon/mission-impossible-android#39]
Thanks so much @SchnWalter! Looks really cool! Couple questions, since you're offline:

- why you you think we need [mapping of the filesystem via yaml and scripting](https://github.com/SchnWalter/mission-impossible-android/blob/python-tools/templates/mia-default/settings.yaml#L12-L33) that goes into the update.zip? It would seem to make sense to have it mirror the structure of the compresses zip, which in turn reflects the structure of the android filesystem.

**Comment by SchnWalter** [comment]
Basically this happed because at the beginging I didn't see a way to add a folder to the archive using python (I'm new to python)... And I eventually ended up needing that functionality and I didn't bother to remove things that were already implemented.

And I of also feel better about an explicit mapping instead of excluding things that we don't need in the archive.

I was also thinking of replacing [set_open_recovery_script()](https://github.com/SchnWalter/mission-impossible-android/blob/python-tools/mia/helpers/android.py#L70-L87) with mapping information, this way you will have all the information about what goes onto the device in one place and you don't have to wonder what else the script will install.

P.S. We should also start adding more documentation, one should be able to run "mia --help" and figure out how to use the command. Or maybe also have a man page generated if we make the python setuptools "installer" work.

**Comment by mikeperry-tor** [comment]
I think this is merged? Closing it to triage the issue list.

**Comment by patcon** [comment]
:+1: thanks mike
