### ISSUE TITLE
Add solution for getting around captive portals

### ISSUE THREAD

**Issue by patcon** [patcon/mission-impossible-android#5]
Ref: [IRC](https://botbot.me/freenode/fdroid/2014-11-21/?msg=25999607&page=2)

Best solution for now is probably to leave the stock browser, but replace it on the home screen with orfox. We could rename the icon to "unsafe browser", and point the home page to local page with a warning about only using this browser for captive portals. (Not quite as elegant as the tails os solution, but simple enough.)

**Comment by mikeperry-tor** [comment]
It turns out that all DNS in CM11+ is done as the root uid. That makes it less safe and less reliable to use non-Firefox browsers as the captive portal browser. It looks like OrWall fixed the issue by temporarily allowing all DNS through while the captive portal browser is active (https://github.com/EthACKdotOrg/orWall/issues/60).

However it is the case that Firefox-based browsers perform their own resolution rather than using the Android resolver. It is also the case that there are now 2 Firefox browsers in F-Droid: the official [Mozilla Firefox build](https://f-droid.org/repository/browse/?fdid=org.mozilla.firefox ), and the FDroid build of [Fennec](https://f-droid.org/repository/browse/?fdid=org.mozilla.fennec_fdroid).

Therefore, in my pull request, I configured OrWall to use Fennec as the "Unsafe browser" for now. If we find it acceptable to have two versions of Firefox installed long term, we could rebrand Fennec to be the "Unsafe Browser", and request a preference from OrWall to stop the blanket DNS allow during captive portal bypass for us.

I am also wary of using the internal browser app, even if the OrWall workaround was 100% safe, because the Browser app is an ancient WebKit derivative that receives no security updates from either Google or Cyanogen. Otherwise I would suggest rebranding the [Lightning Browser](https://f-droid.org/repository/browse/?fdfilter=browser&fdid=acr.browser.lightning), which is a thin skin around the Browser app.

**Comment by patcon** [comment]
Thanks, much of this is new info for me.

It makes sense, but can you clarify why we need separate "safe" and "unsafe" browser apps? Is it that we expect to customize the safe one with plugins and certain config that the unsafe one won't need?

FYI we actually have 3 FF browsers fwiw: 1) F-Droid's Fennec, 2) official FF and 3) GP's Orfox. Does that change anything? Could we not use either Fennec or FF as the unsafe, and encourage Orfox as safe?

Finally, given your concerns, think we should we remove the native browser in `updater-script`?

**Comment by patcon** [comment]
Also, some alternative launchers allow you to rename app icons, which might be worth investigating for designating one browser as unsafe:
https://f-droid.org/repository/browse/?fdfilter=launcher&fdpage=1&page_id=0

**Comment by patcon** [comment]
OK, this is my understanding of the situation:

- For now, safe browser is FF official, unsafe browser is Fennec FDroid (dev)
- When Orfox is more stable, safe is Orfox, unsafe is FF official

And regardless, we're good to remove the stock browser for now.

Sound about right?

**Comment by patcon** [comment]
Aside from rebranding fdroid' browser as unsafe, this is done
